name: Compile Typst to PDF

on:
  push:
    branches:
      - 'stage'
    tags:
      - 'v*'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: fontist/setup-fontist@5b6d1701dcd68e2941068fc7e2d65a81bfb907d1
        with:
          cache-dependency-path: .fontist/manifest.yml
      - run: fontist manifest-install manifest.yml
      - uses: typst-community/setup-typst@v4
      - run: typst compile main.typ main.pdf --font-path ~/.fontist/fonts
      - uses: actions/upload-artifact@v4
        with:
          name: main
          path: main.pdf

  release:
    runs-on: ubuntu-latest
    needs: compile
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: main
      - uses: softprops/action-gh-release@v2
        with:
          files: main.pdf