name: Compile Typst to PDF

on:
  push:
    branches:
      - 'stage'
      - 'test'
    tags:
      - 'v*'

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache Fontist Fonts
        id: cache-fonts
        uses: actions/cache@v4
        with:
          path: ~/.fontist/fonts
          key: ${{ runner.os }}-font-${{ hashFiles('.fontist/manifest.yml') }}

      - name: Set up Ruby and Cache Gems
        uses: ruby/setup-ruby@v1
        if: steps.cache-fonts.outputs.cache-hit != 'true'
        with:
          ruby-version: '3.3' 
          bundler-cache: true

      - name: Install Fontist with Cache
        run: gem install fontist
        if: steps.cache-fonts.outputs.cache-hit != 'true'

      - run: fontist manifest-install .fontist/manifest.yml
        if: steps.cache-fonts.outputs.cache-hit != 'true'

      - uses: typst-community/setup-typst@v4
      - run: typst compile main.typ main.pdf --font-path ~/.fontist/fonts
      - uses: actions/upload-artifact@v4
        with:
          name: main
          path: main.pdf

  release:
    runs-on: ubuntu-latest
    needs: compile
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: main
      - name: Rename PDF for Release
        run: mv main.pdf typst-${{ github.ref_name }}.pdf
      - uses: softprops/action-gh-release@v2
        with:
          files: typst-${{ github.ref_name }}.pdf